char = { !("(" | ")" | WHITESPACE) ~ ANY }
name = @{ char+ }

var = { "def" ~ "(" ~ name ~ ")" }
unsupported = _{ "<unsupported>" }
not = { "!" ~ expr }
and = { "(" ~ expr ~ "&" ~ expr ~ ("&" ~ expr)* ~ ")" }
or = { "(" ~ expr ~ "|" ~ expr ~ ("|" ~ expr)* ~ ")" }
paren_expr = _{ "(" ~ expr ~ ")" }
expr = _{ var | unsupported | not | and | or | paren_expr }

comment = _{ "#" ~ ANY* }
line = _{ SOI ~ (expr | comment | WHITESPACE*) ~ EOI }
WHITESPACE = _{ " " | "\t" }