char = { !("(" | ")" | WHITESPACE | NEWLINE) ~ ANY }
name = @{ char+ }

var = { "def" ~ "(" ~ #var = name ~ ")" } // what about implicit vars?
not = { "!" ~ expr }
and = { "(" ~ expr ~ "&" ~ expr ~ ("&" ~ expr)* ~ ")" } // what about implicit ()?
or = { "(" ~ expr ~ "|" ~ expr ~ ("|" ~ expr)* ~ ")" }
expr = _{ var | not | and | or }

comment = _{ "#" ~ (!NEWLINE ~ ANY)* }
line = _{ expr | comment }
file = _{ SOI ~ (line? ~ NEWLINE)* ~ line? ~ EOI }
WHITESPACE = _{ " " | "\t" }