char = { !("(" | ")" | WHITESPACE) ~ ANY }
name = @{ char+ }

var = { "def" ~ "(" ~ name ~ ")" }
unsupported = _{ "<unsupported>" }
not = { "!" ~ expr }
and = { "(" ~ expr ~ "&" ~ expr ~ ("&" ~ expr)* ~ ")" }
or = { "(" ~ expr ~ "|" ~ expr ~ ("|" ~ expr)* ~ ")" }
expr = _{ var | unsupported | not | and | or }

comment = _{ "#" ~ ANY* }
line = _{ SOI ~ (expr | comment) ~ EOI }
WHITESPACE = _{ " " | "\t" }